name: KickAll
description: Implement the kickall command.
author: DjDCH
main: com.djdch.bukkit.kickall.KickAll
version: 1.0

commands:
  kickall:
    description: Kick all the connected players.
    usage: /<command> (custom message)

permissions:
    kickall.*:
        description: Gives access to all commands
    kickall.kickall:
        description: Gives access to kickall command
        default: op
